In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df1 = pd.read_csv('titanic.csv', index_col='PassengerId')
df1.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df2 = pd.read_csv('titanic.csv', usecols=['Survived', 'Name', 'Sex', 'Ticket'])
df2.head(10)

,Survived,Name,Sex,Ticket
0,0,"Braund, Mr. Owen Harris",male,A/5 21171
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599
2,1,"Heikkinen, Miss. Laina",female,STON/O2. 3101282
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803
4,0,"Allen, Mr. William Henry",male,373450
5,0,"Moran, Mr. James",male,330877
6,0,"McCarthy, Mr. Timothy J",male,17463
7,0,"Palsson, Master. Gosta Leonard",male,349909
8,1,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,347742
9,1,"Nasser, Mrs. Nicholas (Adele Achem)",female,237736

In [24]:
df3 = pd.read_csv('titanic.csv', usecols=['Name', 'Sex', 'Age'], skiprows=[2, 4])
df3.head()

                       Name     Sex   Age
0   Braund, Mr. Owen Harris    male  22.0
1    Heikkinen, Miss. Laina  female  26.0
2  Allen, Mr. William Henry    male  35.0
3          Moran, Mr. James    male   NaN
4   McCarthy, Mr. Timothy J    male  54.0

In [26]:
df3['Age'].dtype

dtype('float64')

In [31]:
df4 = pd.read_csv('titanic.csv', usecols=['Name', 'Sex', 'Age'], )
df4['Age'] = df['Age'].fillna(34).astype(int)
df4.head()

                                                Name     Sex  Age
0                            Braund, Mr. Owen Harris    male   22
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38
2                             Heikkinen, Miss. Laina  female   26
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35
4                           Allen, Mr. William Henry    male   35

In [32]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [33]:
def ren(Sex):
    if Sex == 'male':
        return "MALE"
    else:
        return "FEMALE"

In [34]:
df5 = pd.read_csv('titanic.csv', usecols=['Name', 'Sex', 'Age', 'Ticket'], converters={'Sex': ren})
df5.head()

,Name,Sex,Age,Ticket
0,"Braund, Mr. Owen Harris",MALE,22.0,A/5 21171
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",FEMALE,38.0,PC 17599
2,"Heikkinen, Miss. Laina",FEMALE,26.0,STON/O2. 3101282
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",FEMALE,35.0,113803
4,"Allen, Mr. William Henry",MALE,35.0,373450

In [39]:
df6 = pd.read_csv('titanic.csv', chunksize=100)

for i in df6:
    print(i.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
     PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male
102          103         0       1         White, Mr. Richard Frasar    male
103          104         0       3        Johansson, Mr. Gustaf Joel    male
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked
100  28.0      0      0   349245   7.8958   NaN        S
101   NaN      0      0   349215   7.8958   NaN        S
102  21.0      0      1    35281  77.2875   D26        S
103  33.0      0      0     7540   8.6542   NaN        S
104  37.0      2      0  3101276   7.9250   NaN        S
     PassengerId  Survived  Pclass                            Name   Sex  \
200          201         0       3  Vande Walle, Mr. Nestor Cyriel  male
201          202         0       3             Sage, Mr. Frederick  male
202          203         0       3      Johanson, Mr. Jakob Alfred  male
203          204         0       3            Youseff, Mr. Gerious  male
204          205         1       3        Cohen, Mr. Gurshon "Gus"  male

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked
200  28.0      0      0    345770   9.5000   NaN        S
201   NaN      8      2  CA. 2343  69.5500   NaN        S
202  34.0      0      0   3101264   6.4958   NaN        S
203  45.5      0      0      2628   7.2250   NaN        C
204  18.0      0      0  A/5 3540   8.0500   NaN        S
     PassengerId  Survived  Pclass                                      Name  \
300          301         1       3  Kelly, Miss. Anna Katherine "Annie Kate"
301          302         1       3                        McCoy, Mr. Bernard
302          303         0       3           Johnson, Mr. William Cahoone Jr
303          304         1       2                       Keane, Miss. Nora A
304          305         0       3         Williams, Mr. Howard Hugh "Harry"

        Sex   Age  SibSp  Parch    Ticket   Fare Cabin Embarked
300  female   NaN      0      0      9234   7.75   NaN        Q
301    male   NaN      2      0    367226  23.25   NaN        Q
302    male  19.0      0      0      LINE   0.00   NaN        S
303  female   NaN      0      0    226593  12.35  E101        Q
304    male   NaN      0      0  A/5 2466   8.05   NaN        S
     PassengerId  Survived  Pclass                            Name     Sex  \
400          401         1       3              Niskanen, Mr. Juha    male
401          402         0       3                 Adams, Mr. John    male
402          403         0       3        Jussila, Miss. Mari Aina  female
403          404         0       3  Hakkarainen, Mr. Pekka Pietari    male
404          405         0       3         Oreskovic, Miss. Marija  female

      Age  SibSp  Parch             Ticket     Fare Cabin Embarked
400  39.0      0      0  STON/O 2. 3101289   7.9250   NaN        S
401  26.0      0      0             341826   8.0500   NaN        S
402  21.0      1      0               4137   9.8250   NaN        S
403  28.0      1      0   STON/O2. 3101279  15.8500   NaN        S
404  20.0      0      0             315096   8.6625   NaN        S
     PassengerId  Survived  Pclass                            Name     Sex  \
500          501         0       3                Calic, Mr. Petar    male
501          502         0       3             Canavan, Miss. Mary  female
502          503         0       3  O'Sullivan, Miss. Bridget Mary  female
503          504         0       3  Laitinen, Miss. Kristina Sofia  female
504          505         1       1           Maioni, Miss. Roberta  female

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked
500  17.0      0      0  315086   8.6625   NaN        S
501  21.0      0      0  364846   7.7500   NaN        Q
502   NaN      0      0  330909   7.6292   NaN        Q
503  37.0      0      0    4135   9.5875   NaN        S
504  16.0      0      0  110152  86.5000   B79        S
     PassengerId  Survived  Pclass  \
600          601         1       2
601          602         0       3
602          603         0       1
603          604         0       3
604          605         1       1

                                                  Name     Sex   Age  SibSp  \
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0      2
601                               Slabenoff, Mr. Petco    male   NaN      0
602                          Harrington, Mr. Charles H    male   NaN      0
603                          Torber, Mr. Ernst William    male  44.0      0
604                    Homer, Mr. Harry ("Mr E Haven")    male  35.0      0

     Parch  Ticket     Fare Cabin Embarked
600      1  243847  27.0000   NaN        S
601      0  349214   7.8958   NaN        S
602      0  113796  42.4000   NaN        S
603      0  364511   8.0500   NaN        S
604      0  111426  26.5500   NaN        C
     PassengerId  Survived  Pclass  \
700          701         1       1
701          702         1       1
702          703         0       3
703          704         0       3
704          705         0       3

                                                  Name     Sex   Age  SibSp  \
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.0      1
701                   Silverthorne, Mr. Spencer Victor    male  35.0      0
702                              Barbara, Miss. Saiide  female  18.0      0
703                              Gallagher, Mr. Martin    male  25.0      0
704                            Hansen, Mr. Henrik Juul    male  26.0      1

     Parch    Ticket      Fare    Cabin Embarked
700      0  PC 17757  227.5250  C62 C64        C
701      0  PC 17475   26.2875      E24        S
702      1      2691   14.4542      NaN        C
703      0     36864    7.7417      NaN        Q
704      0    350025    7.8542      NaN        S
     PassengerId  Survived  Pclass  \
800          801         0       2
801          802         1       2
802          803         1       1
803          804         1       3
804          805         1       3

                                            Name     Sex    Age  SibSp  Parch  \
800                         Ponesell, Mr. Martin    male  34.00      0      0
801  Collyer, Mrs. Harvey (Charlotte Annie Tate)  female  31.00      1      1
802          Carter, Master. William Thornton II    male  11.00      1      2
803              Thomas, Master. Assad Alexander    male   0.42      0      1
804                      Hedman, Mr. Oskar Arvid    male  27.00      0      0

         Ticket      Fare    Cabin Embarked
800      250647   13.0000      NaN        S
801  C.A. 31921   26.2500      NaN        S
802      113760  120.0000  B96 B98        S
803        2625    8.5167      NaN        C
804      347089    6.9750      NaN        S