In [4]:
import numpy as np
import pandas as pd

In [5]:
df1 = pd.read_csv('Countries.csv')

In [8]:
df1

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [15]:
# Which Country has the highest population

hPop = df1["population"].idxmax()
locHPop = df1.loc[hPop]
print("Country with the highest population: " , locHPop["country"])

Country with the highest population:  India

In [17]:
# What is the capital of the country with the highest population

locHPopCapital = locHPop["capital_city"]
print("Capital of the country with the highest population: ", locHPopCapital)

Capital of the country with the highest population:  New Delhi

In [19]:
# Which Country has the least population

lPop = df1["population"].idxmin()
locLPop = df1.loc[lPop]
print("Country with the least population: ", locLPop["country"])

Country with the least population:  Tuvalu

In [21]:
# What is the capital of the country with the least population

locLPopCapital = locLPop["capital_city"]
print("capital of the country with the least population: ", locLPopCapital)

capital of the country with the least population:  Funafuti

In [24]:
# Give me top 5 countries with the highest democratic score

df2 = df1.sort_values(by= "democracy_score", ascending= False)
df2[["democracy_score", "country"]].head(5)

     democracy_score      country
127             9.87       Norway
74              9.58      Iceland
164             9.39       Sweden
122             9.26  New Zealand
46              9.22      Denmark

In [34]:
# How many total regions are there(unique)

df1UniqueRegion = pd.DataFrame(df1["region"].unique())
df1UniqueRegion

                            0
0               Southern Asia
1             Southern Europe
2             Northern Africa
3               Middle Africa
4                   Caribbean
5               South America
6                Western Asia
7   Australia and New Zealand
8              Western Europe
9              Eastern Europe
10            Central America
11             Western Africa
12            Southern Africa
13         South-Eastern Asia
14             Eastern Africa
15           Northern America
16               Eastern Asia
17            Northern Europe
18                  Melanesia
19               Central Asia
20                 Micronesia
21                  Polynesia

In [15]:
# How many countries lie in eastern europe region 

regions = pd.DataFrame(df1["region"].value_counts())
regions
regions.loc["Eastern Europe"]

count    10
Name: Eastern Europe, dtype: int64

In [18]:
df1[df1["region"] == "Eastern Europe"]["country"]

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: object

In [26]:
#Who is the political Leader of the 2nd highest populated Country

populationInDESC = df1.sort_values(by= "population", ascending= False)

print("political Leader of the 2nd highest populated Country is - ", populationInDESC.iloc[1]["political_leader"])

political Leader of the 2nd highest populated Country is -  Xi Jinping

In [42]:
# How many countries are there whoes political leaders are unknown

df1[df1["political_leader"].isnull()]["country"]

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: object

In [43]:
print("Number of Unkown Political Leader countries: ", df1[df1["political_leader"].isnull()]["country"].count())

Number of Unkown Political Leader countries:  7

In [46]:
# How many country have Republic in their full name

df1[df1["country_long"].str.contains("Republic", na= False)]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Vanuatu,Republic of Vanuatu,Vanuatu vatu,Port Vila,Melanesia,Oceania,Ni-Vanuatu,-16.000000,167.000000,1870.0,...,326740,1.92308,242389,84351,0.00,0.00,Unknown,15.6,Charlot Salwai,Prime Minister
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [68]:
#Which country in african region has highest population

africanCountries = df1[df1["continent"] == "Africa"]
africanCountries.sort_values(by = "population",ascending= False, inplace= True)

print("Highly populated country in africa: ", africanCountries["country"].iloc[0])

Highly populated country in africa:  Nigeria

C:\Users\goura\AppData\Local\Temp\ipykernel_9964\1806850379.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  africanCountries.sort_values(by = "population",ascending= False, inplace= True)